** Abstract


The repository collects the /sources/ of the ``Engima'' project (Enigma
reloaded, for engineering students, winter semester 2004/2005, at the
University Kiel.

For the webpages of the course project (for summer semester 2003), see
[[http://heim.ifi.uio.no/msteffen/teaching/softtech/ss03/swpraktikum-enigma/][here]].






** Historical notes

The repository has been resurrected by migrating it xfrom ~cvs~ via svn
(using ~cvs2svn~) and from there to ~git~. Caveats concerning missing
branches apply.  Also, original /authors/ may not have been preserved, as
the original development was done all via a common login ~swprakt~ which
therefore did not log the author; in general, the contributors were
students in the course plus the course teachers.

/Remark:/ the course was given also summer semester 2003 (with more
students), but the sources of the semester seem to have been lost. Also an
earlier version of the course exists (given by the chair of theoretical
computer science) and this course builds upon it.





